stages:
  - audit
  - deploy

packj-audit-job:
  stage: audit
  image: docker:20.10.16
  services:
    - docker:dind # necessary for docker run

  script:
    - docker run -d --name packj-container -v /tmp:/tmp/packj -t ossillate/packj:latest help
    - docker cp ./requirements.txt packj-container:/tmp/requirements.txt
    - docker exec -t packj-container sh "ls -al"
    - docker run -v /tmp:/tmp/packj -t ossillate/packj:latest audit -f pypi:/tmp/requirements.txt

comment-job:
  stage: deploy
  environment: production
  script:
    - echo "Adding comment to PR..."
