stages:
  - audit
  - deploy

packj-audit-job:
  stage: audit
  image: docker:latest
  services:
    - docker:dind # necessary for docker run

  script:
    - docker run --name packj-container -v /tmp:/tmp/packj ossillate/packj:latest
    - docker cp ./requirements.txt packj-container:/tmp
    - docker run -v /tmp:/tmp/packj -t ossillate/packj:latest audit -f pypi:/tmp/requirements.txt

comment-job:
  stage: deploy
  environment: production
  script:
    - echo "Adding comment to PR..."
