stages:
  - audit
  - deploy

variables:
  # CHANGE: your dependency files in the format of `<package-manager>:/tmp/packj/<your-dependency-file>`
  DEPENDENCY_FILES: pypi:/tmp/packj/requirements.txt

packj-audit-job:
  stage: audit
  image: docker:20.10.16
  services:
    - docker:dind # necessary for docker run

  script:
    - docker run --name packj-container -v /tmp:/tmp/packj -t ossillate/packj:latest
    - docker cp ./requirements.txt packj-container:/tmp/packj/requirements.txt
    - docker run -v /tmp:/tmp/packj -t ossillate/packj:latest audit -f $DEPENDENCY_FILES

comment-job:
  stage: deploy
  environment: production
  script:
    - echo "Adding comment to PR..."
