stages:
  - audit
  - deploy

variables:
  DEPENDENCY_FILES: requirements.txt # CHANGE: your dependency files

packj-audit-job:
  stage: audit
  image: docker:20.10.16
  services:
    - docker:dind # necessary for docker run

  script:
    - echo $DEPENDENCY_FILES
    - cat parse_script.sh | /bin/bash $DEPENDENCY_FILES
    - docker run --name packj-container -v /tmp:/tmp/packj -t ossillate/packj:latest
    - docker cp ./requirements.txt packj-container:/tmp/packj/requirements.txt
    - docker run -v /tmp:/tmp/packj -t ossillate/packj:latest audit -f $(cat input_files.txt)

comment-job:
  stage: deploy
  environment: production
  script:
    - echo "Adding comment to PR..."
