stages:
  - audit
  - deploy

packj-audit-job:
  stage: audit
  image: docker:20.10.16
  services:
    - docker:dind # necessary for docker run

  script:
    - docker run -v /tmp:/tmp/packj -t ossillate/packj:latest
    - docker cp ./requirements.txt packj-container:/tmp/packj/requirements.txt
    - docker run -t ossillate/packj:latest audit -f pypi:/tmp/packj/requirements.txt

comment-job:
  stage: deploy
  environment: production
  script:
    - echo "Adding comment to PR..."
