stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job: # This job runs in the build stage, which runs first.
  stage: build
  image: python:latest
  script:
    - echo "Pulling Python from Docker..."

packj-audit-job:
  stage: test
  script:
    # - apt-get install python3-venv
    - git clone https://github.com/ossillate-inc/packj
    # - python3 -m venv venv
    # - source ./venv/bin/activate
    - pip3 install -r ./packj/requirements.txt
    # - python3 ./packj/main.py audit -f requirements.txt
    - ls -al

comment-job:
  stage: deploy
  environment: production
  script:
    - echo "Adding comment to PR..."
